[package]
name = "cookie"
version = "0.2.0"
authors = ["Zach Pomerantz <zmp@umich.edu>"]

[lib]
name = "cookie"
path = "src/lib.rs"

[dependencies]
iron = "*"
plugin = "*"
persistent = "*"
modifier = "*"
cookie = "*"
